### ISSUE TITLE
undeclared variable

### ISSUE THREAD

**Issue by LFBernardo** [cldrn/nmap-nse-scripts#3]
Hi,

Got this when testing. 

NSE: SMB: Invalid NTLM challenge message: unexpected signature.
NSE: smb-vuln-ms17-010 against xxx.xxx.xxx.xxx threw an error!
/usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:82: variable 'debug1' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nselib/strict.lua:80: in function '__index'
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:82: in function 'check_ms17010'
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:163: in function </usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:141>
        (...tail calls...)

Thought it may be helpful.

**Comment by SirBabak** [comment]
Hi i'm getting few errors and it failed, here is the debug.

NSE: smb-vuln-ms17-010 against 10.101.2.2 threw an error!
C:\Program Files (x86)\Nmap/scripts\smb-vuln-ms17-010.nse:91: attempt to call field 'pack' (a nil value)
stack traceback:
C:\Program Files (x86)\Nmap/scripts\smb-vuln-ms17-010.nse:91: in function 'check_ms17010'
C:\Program Files (x86)\Nmap/scripts\smb-vuln-ms17-010.nse:160: in function <C:\Program Files (x86)\Nmap/scripts\Arkadin2.nse:138> (...tail calls...)

**Comment by scritchplouf** [comment]
Hi, 
I replaced debug1 by print_debug and it's fine.
However, I have the same problem than SirBabak with pack: 

NSE: SMB: Invalid NTLM challenge message: unexpected signature.
NSE: Connected to share 'IPC$'
NSE: smb-vuln-ms17-010 against X.X.X.X threw an error!
/usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:91: attempt to call field 'pack' (a nil value)
stack traceback:
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:91: in function 'check_ms17010'
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:160: in function </usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:138>
        (...tail calls...)

Thanks !

**Comment by cristianmenghi** [comment]
Hi, same error in nmap 6.40 Lua 5.2 ubuntu 14.04 :


Initiating NSE at 08:57
NSE: SMB: Added account '' to account list
NSE: SMB: Added account 'guest' to account list
NSE: SMB: Invalid NTLM challenge message: unexpected signature.
NSE: smb-vuln-ms17-010 against 192.168.3.13 threw an error!
/usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:88: variable 'debug1' is not declared
stack traceback:
        [C]: in function 'error'
        /usr/bin/../share/nmap/nselib/strict.lua:80: in function '__index'
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:88: in function 'check_ms17010'
        /usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:163: in function </usr/bin/../share/nmap/scripts/smb-vuln-ms17-010.nse:141>
        (...tail calls...)

**Comment by kainzjoh** [comment]
Hi,
please check you're running an up-to-date version of nmap with lua5.3 ex:
```
Nmap version 7.40 ( https://nmap.org )
Platform: x86_64-apple-darwin16.3.0
Compiled with: liblua-5.3.3 openssl-1.0.2j nmap-libpcre-7.6 libpcap-1.8.1 nmap-libdnet-1.12 ipv6
```

**Comment by cldrn** [comment]
Please make sure you are running the latest Nmap version. Nmap 7.x uses Lua 5.3 and unfortunately scripts aren't backwards compatible!

**Comment by scritchplouf** [comment]
I confirm that updating to Lua 5.3 make it works.
Thanks a lot.
