### ISSUE TITLE
smb-vuln-ms17-010: ERROR: Script execution failed (use -d to debug)

### ISSUE THREAD

**Issue by joy-nunes** [cldrn/nmap-nse-scripts#9]
This error is being displayed in the script output, does this mean that I am safe?
![exit2](https://cloud.githubusercontent.com/assets/19313469/26122518/2cc02504-3a4e-11e7-94f2-1f34c7f4a373.png)

**Comment by idlethreat** [comment]
Confirmed this is throwing an error. From the debug log:

    /opt/smb/nmap-nse-scripts/scripts/smb-vuln-ms17-010.nse:82: variable 'debug1' is not declared

I'm attaching a full debug log to this comment.

[debug.txt](https://github.com/cldrn/nmap-nse-scripts/files/1005673/debug.txt)

UPDATE: Built and installed latest Nmap 7.40 from the site. Confirmed that this is a fix and works as expected. Cheers!

**Comment by dkhromenko** [comment]
_'debug1' is not declared_
Update nmap to latest version.

**Comment by rbaudin** [comment]
New version : https://nmap.org/download.html you will need to compile it !

**Comment by rbaudin** [comment]
New version : https://nmap.org/download.html you will need to compile it !

**Comment by rbaudin** [comment]
New version : https://nmap.org/download.html you will need to compile it !

**Comment by rpenzoil** [comment]
New version : https://nmap.org/download.html you will need to compile it !

**Comment by I-Am-Skoot** [comment]
Here is my error,
```
NSE: smb-vuln-ms17-010 M:21c5490 against ###.###.###.### threw an error!
./WannaCry/smb-vuln-ms17-010.nse:99: attempt to call field 'pack' (a nil value)
stack traceback:
        ./WannaCry/smb-vuln-ms17-010.nse:99: in function 'check_ms17010'
        ./WannaCry/smb-vuln-ms17-010.nse:168: in function <./WannaCry/smb-vuln-ms17-010.nse:146>
        (...tail calls...)
```
I have the full -dd if needed.

**Comment by pyzro** [comment]
I'm getting this error while using zenmap on windows:

```
`E:\programs\nmap/scripts\smb-vuln-ms17-010.nse:94: attempt to call field 'pack' (a nil value)

stack traceback:

	E:\programs\nmap/scripts\smb-vuln-ms17-010.nse:94: in function 'check_ms17010'

	E:\programs\nmap/scripts\smb-vuln-ms17-010.nse:163: in function <E:\programs\nmap/scripts\smb-vuln-ms17-010.nse:141>`
```

**Comment by cldrn** [comment]
It seems you are not using a recent version of Nmap. Install a recent version (7.x) and try again. I also suggest to go over the notes I posted:
[https://github.com/cldrn/nmap-nse-scripts/wiki/Notes-about-smb-vuln-ms17-010](https://github.com/cldrn/nmap-nse-scripts/wiki/Notes-about-smb-vuln-ms17-010)
